/*
 * BALANCEAMENTO CLÁSSICO
 * Valores de edifícios e tropas baseados na configuração clássica de Tribal Wars.
 * A Igreja foi intencionalmente excluída. Tempos foram acelerados para jogo solo.
 */
window.GAME_CONFIG = {
  saveKey: "reinosDeGuerra_save_v1",
  tickMs: 1000,
  autosaveMs: 10000,
  // PIN local para abrir ferramentas administrativas. Em multiplayer real, autenticação deve ficar no servidor.
  adminPin: "2468",
  // Login local para a versão estática. Em multiplayer, mover autenticação para o servidor.
  auth: {
    player: { username: "jogador", password: "123456" },
    admin: { username: "admin", password: "2468" },
  },
  defaultSpeed: 4,
  speedOptions: [1, 2, 4, 8],
  productionPerMinute: { wood: 1, clay: 1, iron: 1 },
  buildCostMultiplier: 1,
  buildTimeMultiplier: 1,
  travelSecondsPerTile: 9,
  mapWidth: 100,
  mapHeight: 100,
  villageDensity: 0.09,
  startingResources: { wood: 500, clay: 500, iron: 400 },
  startingVillage: { name: "Aldeia de jogador", x: 0, y: 0 },
  mapOriginCentered: true,
  // Pontuação-base de toda aldeia inicial. Fazenda, Armazém e Praça de Reuniões
  // começam funcionais, mas seus níveis iniciais não entram na pontuação-base.
  startingVillagePoints: 28,
  // Todos os edifícios aparecem aqui para facilitar a personalização da pontuação inicial.
  // O valor indica quantos níveis iniciais são gratuitos para a pontuação.
  freeStartingPointLevels: {
    keep: 0, barracks: 0, stable: 0, workshop: 0, academy: 0, smithy: 0,
    rally: 0, statue: 0, market: 0, lumber: 0, claypit: 0, mine: 0,
    farm: 1, storage: 1, hide: 0, wall: 0,
  },
  // Configuração clássica de 28 pontos: Principal 1 (10) + Bosque 1 (6)
  // + Barreiro 1 (6) + Mina de Ferro 1 (6). Os pontos são sempre calculados
  // pelos níveis reais dos edifícios; a velocidade do mundo não altera pontuação.
  initialBuildingLevels: {
    keep: 1, barracks: 0, stable: 0, workshop: 0, academy: 0, smithy: 0,
    rally: 1, statue: 0, market: 0, lumber: 1, claypit: 1, mine: 1,
    farm: 1, storage: 1, hide: 0, wall: 0,
  },
  worldName: "Mundo 1",
  mapFrameSizes: [50, 100, 150],
  defaultMapFrameSize: 100,
  unlimitedBuildQueue: false,
  enemiesEnabled: false,
  enemyCount: 0,
  barbarianSpawn: { enabled: true, intervalMinutes: 30, maxNewVillages: 20, perCycle: 1, bonusChance: 15, maximized: false },
  enemyRules: {
    canAttackPlayers: true,
    canAttackBarbarians: true,
    canAttackOtherEnemies: true,
    canConquerOtherEnemies: true,
    canConquer: true,
    canConquerPlayers: true,
    canConquerBarbarians: true,
    maxVillagesPerEnemy: 12,
    attackRadius: 25,
    canRecruitTroops: true,
    canBuild: true,
    canRecruitNobles: true,
    canUseSiege: true,
    canScout: true,
    recruitmentBatch: 20,
    actionIntervalSeconds: 12,
  },
  buildingPresets: {
    halfRatio: 0.5,
    custom: null,
  },
  adminPresets: {
    defenseTroops: { spear: 5000, sword: 5000, archer: 5000,scout: 500, heavy: 1000, catapult: 500 },
    attackTroops: { axe: 7500, light: 3000,scout: 250, ram: 300 },
    attackNoblesTroops: { axe: 7000, light: 2800, scout: 250, ram: 300, noble: 4 },
    customTroops: { spear: 1000, sword: 1000, axe: 1000, archer: 0, scout: 100, light: 500, mounted: 0, heavy: 0, ram: 100, catapult: 100, noble: 0 },
  },
  baseLoyalty: 100,
  bonusDefaults: { chance: 12, wood: 30, clay: 30, iron: 30, farm: 10, resources: 15, barracks: 10, stable: 10, storage: 50 },
  baseVillageDefense: 20,
  conquestLoyaltyDamage: [25, 35],
  productionByLevel: [
    0, 30, 35, 41, 47, 55, 64, 74, 86, 100, 117, 136, 158, 184, 214, 249, 289,
    337, 391, 455, 530, 616, 717, 833, 969, 1127, 1311, 1525, 1774, 2063, 2400,
  ],
  warehouseByLevel: [
    0, 1000, 1229, 1512, 1859, 2285, 2810, 3454, 4247, 5222, 6420, 7893, 9705,
    11932, 14670, 18037, 22177, 27266, 33523, 41222, 50675, 62305, 76604, 94184,
    115798, 142373, 175047, 215258, 264611, 325321, 400000,
  ],
  farmByLevel: [
    0, 240, 281, 329, 386, 452, 530, 622, 729, 855, 1002, 1175, 1378, 1616,
    1895, 2222, 2606, 3055, 3581, 4198, 4921, 5769, 6761, 7925, 9286, 10883,
    12755, 14948, 17518, 20531, 24000,
  ],
  difficulties: {
    easy: { name: "Crescimento lento", aiGrowth: 0.65 },
    normal: { name: "Crescimento normal", aiGrowth: 1 },
    hard: { name: "Crescimento rápido", aiGrowth: 1.45 },
  },
  objectives: {
    villages1: { name: "Conquistar 1 aldeia", type: "conquests", target: 1 },
    villages5: { name: "Conquistar 5 aldeias", type: "conquests", target: 5 },
    villages10: { name: "Conquistar 10 aldeias", type: "conquests", target: 10 },
    map60: { name: "Dominar 60% das aldeias", type: "percentage", target: 60 },
    map100: { name: "Conquistar todo o mundo", type: "percentage", target: 100 },
  },
  ai: { actionIntervalSeconds: 25 },
  bonusTypes: {
    none: { name: "Sem bônus", icon: "" },
    wood: { name: "Madeira", icon: "🪵" },
    clay: { name: "Argila", icon: "🧱" },
    iron: { name: "Ferro", icon: "⛓" },
    farm: { name: "Fazenda", icon: "👥" },
    resources: { name: "Todos os recursos", icon: "✦" },
    barracks: { name: "Quartel", icon: "⚔" },
    stable: { name: "Estábulo", icon: "♞" },
    storage: { name: "Armazém", icon: "▣" },
  },
  buildingPointFactor: 1.2,
  buildings: {
    keep: {
      name: "Edifício Principal",
      icon: "♜",
      description:
        "Reduz o tempo das construções e permite demolições no nível 15.",
      baseCost: { wood: 90, clay: 80, iron: 70 },
      costFactor: { wood: 1.26, clay: 1.275, iron: 1.26 },
      baseTime: 8,
      maxLevel: 30,
      pointBase: 10,
      populationBase: 5, populationFactor: 1.17,
    },
    barracks: {
      name: "Quartel",
      icon: "⚔",
      description: "Recruta unidades de infantaria.",
      baseCost: { wood: 200, clay: 170, iron: 90 },
      costFactor: { wood: 1.26, clay: 1.28, iron: 1.26 },
      baseTime: 12,
      maxLevel: 25,
      pointBase: 16,
      populationBase: 7, populationFactor: 1.17,
      requires: { keep: 3 },
    },
    stable: {
      name: "Estábulo",
      icon: "♞",
      description: "Recruta batedores e cavalaria.",
      baseCost: { wood: 270, clay: 240, iron: 260 },
      costFactor: { wood: 1.26, clay: 1.28, iron: 1.26 },
      baseTime: 20,
      maxLevel: 20,
      pointBase: 20,
      populationBase: 8, populationFactor: 1.17,
      requires: { keep: 10, barracks: 5, smithy: 5 },
    },
    workshop: {
      name: "Oficina",
      icon: "⚒",
      description: "Produz aríetes e catapultas.",
      baseCost: { wood: 300, clay: 240, iron: 260 },
      costFactor: { wood: 1.26, clay: 1.28, iron: 1.26 },
      baseTime: 22,
      maxLevel: 15,
      pointBase: 24,
      populationBase: 10, populationFactor: 1.17,
      requires: { keep: 10, smithy: 10 },
    },
    academy: {
      name: "Academia",
      icon: "♛",
      description: "Forma Nobres para conquistar aldeias.",
      baseCost: { wood: 15000, clay: 25000, iron: 10000 },
      costFactor: { wood: 2, clay: 2, iron: 2 },
      baseTime: 55,
      maxLevel: 1,
      pointBase: 512,
      populationBase: 80, populationFactor: 1,
      requires: { keep: 20, smithy: 20, market: 10 },
    },
    smithy: {
      name: "Ferreiro",
      icon: "⚙",
      description: "Desbloqueia novas unidades militares.",
      baseCost: { wood: 220, clay: 180, iron: 240 },
      costFactor: { wood: 1.26, clay: 1.275, iron: 1.26 },
      baseTime: 20,
      maxLevel: 20,
      pointBase: 24,
      populationBase: 20, populationFactor: 1.17,
      requires: { keep: 5, barracks: 1 },
    },
    rally: {
      name: "Praça de Reuniões",
      icon: "⚑",
      description: "Ponto de comando das tropas.",
      baseCost: { wood: 10, clay: 40, iron: 30 },
      costFactor: { wood: 1.26, clay: 1.275, iron: 1.26 },
      baseTime: 5,
      maxLevel: 1,
      pointBase: 0,
      populationBase: 0, populationFactor: 1,
    },
    statue: {
      name: "Estátua",
      icon: "♝",
      description: "Permite convocar o Paladino.",
      baseCost: { wood: 220, clay: 220, iron: 220 },
      costFactor: { wood: 1, clay: 1, iron: 1 },
      baseTime: 10,
      maxLevel: 1,
      pointBase: 24,
      populationBase: 10, populationFactor: 1,
    },
    market: {
      name: "Mercado",
      icon: "⚖",
      description: "Organiza comércio e é requisito da Academia.",
      baseCost: { wood: 100, clay: 100, iron: 100 },
      costFactor: { wood: 1.26, clay: 1.275, iron: 1.26 },
      baseTime: 10,
      maxLevel: 25,
      pointBase: 10,
      populationBase: 20, populationFactor: 1.17,
      requires: { keep: 3, storage: 2 },
    },
    lumber: {
      name: "Bosque",
      icon: "♣",
      description: "Produz madeira continuamente.",
      baseCost: { wood: 50, clay: 60, iron: 40 },
      costFactor: { wood: 1.25, clay: 1.275, iron: 1.25 },
      baseTime: 5,
      maxLevel: 30,
      pointBase: 6,
      populationBase: 5, populationFactor: 1.155,
    },
    claypit: {
      name: "Barreiro",
      icon: "◆",
      description: "Produz argila continuamente.",
      baseCost: { wood: 65, clay: 50, iron: 40 },
      costFactor: { wood: 1.27, clay: 1.265, iron: 1.24 },
      baseTime: 5,
      maxLevel: 30,
      pointBase: 6,
      populationBase: 10, populationFactor: 1.14,
    },
    mine: {
      name: "Mina de Ferro",
      icon: "⛏",
      description: "Produz ferro continuamente.",
      baseCost: { wood: 75, clay: 65, iron: 70 },
      costFactor: { wood: 1.252, clay: 1.275, iron: 1.245 },
      baseTime: 6,
      maxLevel: 30,
      pointBase: 6,
      populationBase: 10, populationFactor: 1.14,
    },
    farm: {
      name: "Fazenda",
      icon: "⌂",
      description: "Determina a população máxima.",
      baseCost: { wood: 45, clay: 40, iron: 30 },
      costFactor: { wood: 1.3, clay: 1.32, iron: 1.3 },
      baseTime: 5,
      maxLevel: 30,
      pointBase: 5,
    },
    storage: {
      name: "Armazém",
      icon: "▣",
      description: "Armazena cada tipo de recurso.",
      baseCost: { wood: 60, clay: 50, iron: 40 },
      costFactor: { wood: 1.265, clay: 1.27, iron: 1.245 },
      baseTime: 5,
      maxLevel: 30,
      pointBase: 6,
    },
    hide: {
      name: "Esconderijo",
      icon: "◈",
      description: "Protege parte dos recursos contra saques.",
      baseCost: { wood: 50, clay: 60, iron: 50 },
      costFactor: { wood: 1.25, clay: 1.25, iron: 1.25 },
      baseTime: 5,
      maxLevel: 10,
      pointBase: 5,
      populationBase: 2, populationFactor: 1.17,
    },
    wall: {
      name: "Muralha",
      icon: "▤",
      description: "Aumenta a defesa básica e o poder dos defensores.",
      baseCost: { wood: 50, clay: 100, iron: 20 },
      costFactor: { wood: 1.26, clay: 1.275, iron: 1.26 },
      baseTime: 8,
      maxLevel: 20,
      pointBase: 5,
      populationBase: 5, populationFactor: 1.17,
      requires: { barracks: 1 },
    },
  },
  units: {
    spear: {
      name: "Lanceiro",
      icon: "♙",
      class: "infantry",
      attack: 10,
      defenseInfantry: 15,
      defenseCavalry: 45,
      defenseArcher: 20,
      speedMinutes: 18,
      speed: 1,
      population: 1,
      carry: 25,
      trainSeconds: 3,
      cost: { wood: 50, clay: 30, iron: 10 },
      requires: { barracks: 1 },
    },
    sword: {
      name: "Espadachim",
      icon: "♟",
      class: "infantry",
      attack: 25,
      defenseInfantry: 50,
      defenseCavalry: 15,
      defenseArcher: 40,
      speedMinutes: 22,
      speed: 0.818,
      population: 1,
      carry: 15,
      trainSeconds: 4,
      cost: { wood: 30, clay: 30, iron: 70 },
      requires: { smithy: 1 },
    },
    axe: {
      name: "Bárbaro",
      icon: "🪓",
      class: "infantry",
      attack: 40,
      defenseInfantry: 10,
      defenseCavalry: 5,
      defenseArcher: 10,
      speedMinutes: 18,
      speed: 1,
      population: 1,
      carry: 10,
      trainSeconds: 4,
      cost: { wood: 60, clay: 30, iron: 40 },
      requires: { smithy: 2 },
    },
    archer: {
      name: "Arqueiro",
      icon: "➶",
      class: "archer",
      attack: 15,
      defenseInfantry: 50,
      defenseCavalry: 40,
      defenseArcher: 5,
      speedMinutes: 18,
      speed: 1,
      population: 1,
      carry: 10,
      trainSeconds: 4,
      cost: { wood: 100, clay: 30, iron: 60 },
      requires: { barracks: 5, smithy: 5 },
    },
    scout: {
      name: "Batedor",
      icon: "◉",
      class: "cavalry",
      attack: 0,
      defenseInfantry: 2,
      defenseCavalry: 1,
      defenseArcher: 2,
      speedMinutes: 9,
      speed: 2,
      population: 2,
      carry: 0,
      trainSeconds: 5,
      cost: { wood: 50, clay: 50, iron: 20 },
      requires: { stable: 1 },
    },
    light: {
      name: "Cavalaria Leve",
      icon: "♞",
      class: "cavalry",
      attack: 130,
      defenseInfantry: 30,
      defenseCavalry: 40,
      defenseArcher: 30,
      speedMinutes: 10,
      speed: 1.8,
      population: 4,
      carry: 80,
      trainSeconds: 8,
      cost: { wood: 125, clay: 100, iron: 250 },
      requires: { stable: 3 },
    },
    mounted: {
      name: "Arqueiro a Cavalo",
      icon: "➹",
      class: "cavalry",
      attack: 120,
      defenseInfantry: 40,
      defenseCavalry: 30,
      defenseArcher: 50,
      speedMinutes: 10,
      speed: 1.8,
      population: 5,
      carry: 50,
      trainSeconds: 9,
      cost: { wood: 250, clay: 100, iron: 150 },
      requires: { stable: 5 },
    },
    heavy: {
      name: "Cavalaria Pesada",
      icon: "♘",
      class: "cavalry",
      attack: 150,
      defenseInfantry: 200,
      defenseCavalry: 80,
      defenseArcher: 180,
      speedMinutes: 11,
      speed: 1.636,
      population: 6,
      carry: 50,
      trainSeconds: 12,
      cost: { wood: 200, clay: 150, iron: 600 },
      requires: { stable: 10, smithy: 15 },
    },
    ram: {
      name: "Aríete",
      icon: "▰",
      class: "siege",
      attack: 2,
      defenseInfantry: 20,
      defenseCavalry: 50,
      defenseArcher: 20,
      speedMinutes: 30,
      speed: 0.6,
      population: 5,
      carry: 0,
      trainSeconds: 12,
      cost: { wood: 300, clay: 200, iron: 200 },
      requires: { workshop: 1 },
    },
    catapult: {
      name: "Catapulta",
      icon: "◒",
      class: "siege",
      attack: 100,
      defenseInfantry: 100,
      defenseCavalry: 50,
      defenseArcher: 100,
      speedMinutes: 30,
      speed: 0.6,
      population: 8,
      carry: 0,
      trainSeconds: 15,
      cost: { wood: 320, clay: 400, iron: 100 },
      requires: { workshop: 2, smithy: 12 },
    },
    paladin: {
      name: "Paladino",
      icon: "♝",
      class: "cavalry",
      attack: 150,
      defenseInfantry: 250,
      defenseCavalry: 400,
      defenseArcher: 150,
      speedMinutes: 10,
      speed: 1.8,
      population: 10,
      carry: 100,
      trainSeconds: 25,
      cost: { wood: 20, clay: 20, iron: 40 },
      requires: { statue: 1 },
      limit: 1,
    },
    noble: {
      name: "Nobre",
      icon: "♛",
      class: "infantry",
      attack: 30,
      defenseInfantry: 100,
      defenseCavalry: 50,
      defenseArcher: 100,
      speedMinutes: 35,
      speed: 0.514,
      population: 100,
      carry: 0,
      trainSeconds: 40,
      cost: { wood: 40000, clay: 50000, iron: 50000 },
      requires: { academy: 1, keep: 20, smithy: 20, market: 10 },
    },
  },
};

// Regras do Mundo: qualquer parâmetro de balanceamento pode ser sobrescrito pelo
// Administrador. O saveKey fica de fora de propósito para não "sumir" com saves.
(function applySavedWorldRules(){
  const deepMerge = (target, source) => {
    if (!source || typeof source !== "object") return target;
    Object.entries(source).forEach(([key, value]) => {
      if (key === "saveKey") return;
      if (value && typeof value === "object" && !Array.isArray(value)) {
        if (!target[key] || typeof target[key] !== "object" || Array.isArray(target[key])) target[key] = {};
        deepMerge(target[key], value);
      } else target[key] = value;
    });
    return target;
  };
  try {
    const saved = JSON.parse(localStorage.getItem("reinosDeGuerra_worldRules") || "null");
    if (saved) deepMerge(window.GAME_CONFIG, saved);
  } catch (e) { console.warn("Regras do Mundo inválidas; usando config.js.", e); }
})();
